export const listOfCountries = [
    { name: 'Afghanistan', id: 'AF' },
    { name: 'Albania', id: 'AL' },
    { name: 'Algeria', id: 'DZ' },
    { name: 'Andorra', id: 'AD' },
    { name: 'Angola', id: 'AO' },
    { name: 'Antigua and Barbuda', id: 'AG' },
    { name: 'Argentina', id: 'AR' },
    { name: 'Armenia', id: 'AM' },
    { name: 'Australia', id: 'AU' },
    { name: 'Austria', id: 'AT' },
    { name: 'Azerbaijan', id: 'AZ' },
    { name: 'Bahamas', id: 'BS' },
    { name: 'Bahrain', id: 'BH' },
    { name: 'Bangladesh', id: 'BD' },
    { name: 'Barbados', id: 'BB' },
    { name: 'Belarus', id: 'BY' },
    { name: 'Belgium', id: 'BE' },
    { name: 'Belize', id: 'BZ' },
    { name: 'Benin', id: 'BJ' },
    { name: 'Bhutan', id: 'BT' },
    { name: 'Bolivia (Plurinational State of)', id: 'BO' },
    { name: 'Bosnia and Herzegovina', id: 'BA' },
    { name: 'Botswana', id: 'BW' },
    { name: 'Brazil', id: 'BR' },
    { name: 'Brunei Darussalam', id: 'BN' },
    { name: 'Bulgaria', id: 'BG' },
    { name: 'Burkina Faso', id: 'BF' },
    { name: 'Burundi', id: 'BI' },
    { name: 'Cabo Verde', id: 'CV' },
    { name: 'Cambodia', id: 'KH' },
    { name: 'Cameroon', id: 'CM' },
    { name: 'Canada', id: 'CA' },
    { name: 'Central African Republic', id: 'CF' },
    { name: 'Chad', id: 'TD' },
    { name: 'Chile', id: 'CL' },
    { name: 'China', id: 'CN' },
    { name: 'Colombia', id: 'CO' },
    { name: 'Comoros', id: 'KM' },
    { name: 'Congo', id: 'CG' },
    { name: 'Costa Rica', id: 'CR' },
    { name: "Côte d'Ivoire", id: 'CI' },
    { name: 'Croatia', id: 'HR' },
    { name: 'Cuba', id: 'CU' },
    { name: 'Cyprus', id: 'CY' },
    { name: 'Czechia', id: 'CZ' },
    { name: "Democratic People's Republic of Korea", id: 'KP' },
    { name: 'Democratic Republic of the Congo', id: 'CD' },
    { name: 'Denmark', id: 'DK' },
    { name: 'Djibouti', id: 'DJ' },
    { name: 'Dominica', id: 'DM' },
    { name: 'Dominican Republic', id: 'DO' },
    { name: 'Ecuador', id: 'EC' },
    { name: 'Egypt', id: 'EG' },
    { name: 'El Salvador', id: 'SV' },
    { name: 'Equatorial Guinea', id: 'GQ' },
    { name: 'Eritrea', id: 'ER' },
    { name: 'Estonia', id: 'EE' },
    { name: 'Eswatini', id: 'SZ' },
    { name: 'Ethiopia', id: 'ET' },
    { name: 'Fiji', id: 'FJ' },
    { name: 'Finland', id: 'FI' },
    { name: 'France', id: 'FR' },
    { name: 'Gabon', id: 'GA' },
    { name: 'Gambia', id: 'GM' },
    { name: 'Georgia', id: 'GE' },
    { name: 'Germany', id: 'DE' },
    { name: 'Ghana', id: 'GH' },
    { name: 'Greece', id: 'GR' },
    { name: 'Grenada', id: 'GD' },
    { name: 'Guatemala', id: 'GT' },
    { name: 'Guinea', id: 'GN' },
    { name: 'Guinea-Bissau', id: 'GW' },
    { name: 'Guyana', id: 'GY' },
    { name: 'Haiti', id: 'HT' },
    { name: 'Honduras', id: 'HN' },
    { name: 'Hungary', id: 'HU' },
    { name: 'Iceland', id: 'IS' },
    { name: 'India', id: 'IN' },
    { name: 'Indonesia', id: 'ID' },
    { name: 'Iran (Islamic Republic of)', id: 'IR' },
    { name: 'Iraq', id: 'IQ' },
    { name: 'Ireland', id: 'IE' },
    { name: 'Israel', id: 'IL' },
    { name: 'Italy', id: 'IT' },
    { name: 'Jamaica', id: 'JM' },
    { name: 'Japan', id: 'JP' },
    { name: 'Jordan', id: 'JO' },
    { name: 'Kazakhstan', id: 'KZ' },
    { name: 'Kenya', id: 'KE' },
    { name: 'Kiribati', id: 'KI' },
    { name: 'Kuwait', id: 'KW' },
    { name: 'Kyrgyzstan', id: 'KG' },
    { name: "Lao People's Democratic Republic", id: 'LA' },
    { name: 'Latvia', id: 'LV' },
    { name: 'Lebanon', id: 'LB' },
    { name: 'Lesotho', id: 'LS' },
    { name: 'Liberia', id: 'LR' },
    { name: 'Libya', id: 'LY' },
    { name: 'Liechtenstein', id: 'LI' },
    { name: 'Lithuania', id: 'LT' },
    { name: 'Luxembourg', id: 'LU' },
    { name: 'Madagascar', id: 'MG' },
    { name: 'Malawi', id: 'MW' },
    { name: 'Malaysia', id: 'MY' },
    { name: 'Maldives', id: 'MV' },
    { name: 'Mali', id: 'ML' },
    { name: 'Malta', id: 'MT' },
    { name: 'Marshall Islands', id: 'MH' },
    { name: 'Mauritania', id: 'MR' },
    { name: 'Mauritius', id: 'MU' },
    { name: 'Mexico', id: 'MX' },
    { name: 'Micronesia (Federated States of)', id: 'FM' },
    { name: 'Monaco', id: 'MC' },
    { name: 'Mongolia', id: 'MN' },
    { name: 'Montenegro', id: 'ME' },
    { name: 'Morocco', id: 'MA' },
    { name: 'Mozambique', id: 'MZ' },
    { name: 'Myanmar', id: 'MM' },
    { name: 'Namibia', id: 'NA' },
    { name: 'Nauru', id: 'NR' },
    { name: 'Nepal', id: 'NP' },
    { name: 'Netherlands', id: 'NL' },
    { name: 'New Zealand', id: 'NZ' },
    { name: 'Nicaragua', id: 'NI' },
    { name: 'Niger', id: 'NE' },
    { name: 'Nigeria', id: 'NG' },
    { name: 'North Macedonia', id: 'MK' },
    { name: 'Norway', id: 'NO' },
    { name: 'Oman', id: 'OM' },
    { name: 'Pakistan', id: 'PK' },
    { name: 'Palau', id: 'PW' },
    { name: 'Panama', id: 'PA' },
    { name: 'Papua New Guinea', id: 'PG' },
    { name: 'Paraguay', id: 'PY' },
    { name: 'Peru', id: 'PE' },
    { name: 'Philippines', id: 'PH' },
    { name: 'Poland', id: 'PL' },
    { name: 'Portugal', id: 'PT' },
    { name: 'Qatar', id: 'QA' },
    { name: 'Republic of Korea', id: 'KR' },
    { name: 'Republic of Moldova', id: 'MD' },
    { name: 'Romania', id: 'RO' },
    { name: 'Russian Federation', id: 'RU' },
    { name: 'Rwanda', id: 'RW' },
    { name: 'Saint Kitts and Nevis', id: 'KN' },
    { name: 'Saint Lucia', id: 'LC' },
    { name: 'Saint Vincent and the Grenadines', id: 'VC' },
    { name: 'Samoa', id: 'WS' },
    { name: 'San Marino', id: 'SM' },
    { name: 'Sao Tome and Principe', id: 'ST' },
    { name: 'Senegal', id: 'SN' },
    { name: 'Serbia', id: 'RS' },
    { name: 'Seychelles', id: 'SC' },
    { name: 'Sierra Leone', id: 'SL' },
    { name: 'Singapore', id: 'SG' },
    { name: 'Slovakia', id: 'SK' },
    { name: 'Slovenia', id: 'SI' },
    { name: 'Solomon Islands', id: 'SB' },
    { name: 'Somalia', id: 'SO' },
    { name: 'South Africa', id: 'ZA' },
    { name: 'South Sudan', id: 'SS' },
    { name: 'Spain', id: 'ES' },
    { name: 'Sri Lanka', id: 'LK' },
    { name: 'Sudan', id: 'SD' },
    { name: 'Suriname', id: 'SR' },
    { name: 'Sweden', id: 'SE' },
    { name: 'Switzerland', id: 'CH' },
    { name: 'Syrian Arab Republic', id: 'SY' },
    { name: 'Tajikistan', id: 'TJ' },
    { name: 'Thailand', id: 'TH' },
    { name: 'Timor-Leste', id: 'TL' },
    { name: 'Togo', id: 'TG' },
    { name: 'Tonga', id: 'TO' },
    { name: 'Trinidad and Tobago', id: 'TT' },
    { name: 'Tunisia', id: 'TN' },
    { name: 'Turkey', id: 'TR' },
    { name: 'Turkmenistan', id: 'TM' },
    { name: 'Tuvalu', id: 'TV' },
    { name: 'Uganda', id: 'UG' },
    { name: 'Ukraine', id: 'UA' },
    { name: 'United Arab Emirates', id: 'AE' },
    { name: 'United Kingdom of Great Britain and Northern Ireland', id: 'GB' },
    { name: 'United Republic of Tanzania', id: 'TZ' },
    { name: 'United States of America', id: 'US' },
    { name: 'Uruguay', id: 'UY' },
    { name: 'Uzbekistan', id: 'UZ' },
    { name: 'Vanuatu', id: 'VU' },
    { name: 'Venezuela (Bolivarian Republic of)', id: 'VE' },
    { name: 'Viet Nam', id: 'VN' },
    { name: 'Yemen', id: 'YE' },
    { name: 'Zambia', id: 'ZM' },
    { name: 'Zimbabwe', id: 'ZW' },
]
